### PR TITLE
Add support for RFS-KK* models

### PR DESCRIPTION
**Pull request by HepoH3**
After v1.5 release integration accidentialy dropped support for
RFS-KKL00 kettle which worked perfectly on v1.4 version.
<details>
  <summary>Device page on v1.4</summary>

</details>

<details>
  <summary>Errors on v1.5</summary>

### Error setting up entry RFS-KKL00 (ED:99:2C:79:90:A3) for skykettle

```python
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/skykettle/__init__.py", line 32, in async_setup_entry
    kettle = KettleConnection(
  File "/config/custom_components/skykettle/kettle_connection.py", line 26, in __init__
    super().__init__(model)
  File "/config/custom_components/skykettle/skykettle.py", line 85, in __init__
    raise SkyKettleError("Unknown kettle model")
custom_components.skykettle.skykettle.SkyKettleError: Unknown kettle model
```

</details>

### CODE REVIEW

**Comment by HepoH3** [comment]
As you can see in the [ha_kettler/r4sconst.py](https://github.com/mavrikkk/ha_kettler/blob/master/custom_components/ready4sky/r4sconst.py), there are not only RK-* models, but also:

1. RFS-*
2. RSP-*
3. RCH-*
4. RMC-*

I can't say would all of them work here, but I'm pretty sure that RFS-KKL00 is work just fine.

**Comment by ClusterM** [comment]
Yes, version 1.5 is very untested :(

**Comment by ClusterM** [comment]
> * RFS-*
> * RSP-*
> * RCH-*
> * RMC-*

It's not kettles.

**Comment by HepoH3** [comment]
Seems to work fine. But, if you return `1` for `RFS-KK`, may be you should revert my changes (I've returned `3` and has been add `3` to lists of models, like `elif self.model_code in [1, 2, 3]:`

**Comment by HepoH3** [comment]
> Seems to work fine. But, if you return `1` for `RFS-KK`, may be you should revert my changes (I've returned `3` and has been add `3` to lists of models, like `elif self.model_code in [1, 2, 3]:`

Currently there is a dead code, because `return 3` will never execute in:
```
    def get_model_code(model):
        if model:
            if model.startswith("RK-M1"):
                return 0
            elif model.startswith("RK-G2"):
                return 1
            elif model.startswith("RFS-KK"):
                return 1
            elif model.startswith("RK-M2"):
                return 2
            elif model.startswith("RFS-KK"):
                return 3
        return None
```

**Pull request merged**
