### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by Kvasenok**
Another try to update translations

### CODE REVIEW

**Comment by Kvasenok** [comment]
Ok, now it all should be in compliance with the latest changes in the translation mechanics.

**Comment by ClusterM** [comment]
Thanks. Are you tested it? And you have typo in "water_heater.en.json" - "Hoil+Heat"

**Comment by ClusterM** [comment]
Merged, thank you!

**Comment by ClusterM** [comment]
Translation is not working at all for me. It worked at least partically before.

**Comment by ClusterM** [comment]
Oops, my mistake. Works fine. Thank you!

**Comment by Kvasenok** [comment]
Yeah, it actually needs a few reboots to start working, don't know why though

**Pull request merged**
